#!/usr/bin/env python3
"""
Generate complete EvoASM self-bootstrapping two-pass assembler.
Uses normal BRANCH syntax; the Python assembler v2 auto-generates
long jump code sequences for targets > 255 bytes.
"""
import sys, textwrap

MNEMONICS = [
    ("ABOUND",13),("ALLOC",17),("BRANCH",2),("CREA",63),
    ("DISPERSE",50),("FELLOWSHIP",61),("GATHER",24),("HALT",56),
    ("INCREASE",49),("MERGE",16),("MICRO",12),
    ("PENETRATE",54),("PUSH_UP",6),("RECV",0),("REDUCE",35),("REPLACE",29),
    ("RETURN",1),("SHL",55),("SHR",7),("SPRT",34),
    ("STEP",59),("XOR",37),
]

# EvoASM helper: write a byte to [R5], advance R5
def wb(v):
    if v == 0:
        return "    ZERO\n    DISPERSE R5, R1\n    ABOUND R2, 1\n    INCREASE R5, R2"
    return f"    ABOUND R1, {v}\n    DISPERSE R5, R1\n    ABOUND R2, 1\n    INCREASE R5, R2"

# EvoASM helper: write a string to [R5]
def ws(label, s):
    lines = [f"    ; {label}"]
    for c in s:
        lines.append(wb(ord(c)))
    lines.append(wb(0))
    return "\n".join(lines)

# EvoASM helper: allocate size_kb * 1024 bytes via SYS_MALLOC, result in dst_reg
def alloc_large(dst_reg, size_kb):
    lines = [
        f"    ABOUND R0, 10             ; SYS_MALLOC",
        f"    ABOUND R1, {size_kb}       ; base = {size_kb}",
        f"    ABOUND R14, 10            ; shift = 10 (×1024)",
        f"    SHL R1, R14               ; size = {size_kb}×1024 = {size_kb * 1024}",
        f"    RECV R0, 0",
        f"    FELLOWSHIP {dst_reg}, R0",
    ]
    return "\n".join(lines)

def gen():
    L = []
    def add(s=""): L.append(s)

    add("; ===== EvoASM Self-Bootstrapping Two-Pass Assembler v2.0 =====")
    add("; Assembled by Python assembler v2 (auto long-jump support)")
    add("")

    # ===== Macros =====
    add("; ===== Macros =====")
    add("%macro ZERO 0")
    add("    ABOUND R1, 16")
    add("    ABOUND R2, 16")
    add("    REDUCE R1, R2")
    add("%endmacro")
    add("")
    add("%macro WB 1")
    add("    ABOUND R1, %1")
    add("    DISPERSE R5, R1")
    add("    ABOUND R2, 1")
    add("    INCREASE R5, R2")
    add("%endmacro")
    add("")
    add("%macro WB0 0")
    add("    ZERO")
    add("    DISPERSE R5, R1")
    add("    ABOUND R2, 1")
    add("    INCREASE R5, R2")
    add("%endmacro")
    add("")
    add("%macro LOADB 2")
    add("    ZERO")
    add("    FELLOWSHIP %1, R0")
    add("    PENETRATE %2, %1")
    add("%endmacro")
    add("")

    # ===== Constants =====
    add("; ===== Constants =====")
    for n,v in [("SYS_OPEN",0),("SYS_READ",1),("SYS_WRITE",2),
                 ("SYS_CLOSE",3),("SYS_PRINT",40),("SYS_EXIT",255),
                 ("SYS_MALLOC",10)]:
        add(f"{n} EQU {v}")
    add("MODE_READ EQU 0")
    add("MODE_WRITE EQU 1")
    for n,v in [("CHAR_NL",10),("CHAR_SP",32),("CHAR_SEMI",59),
                 ("CHAR_COLON",58),("CHAR_COMMA",44),("CHAR_0",48)]:
        add(f"{n} EQU {v}")
    for n,v in MNEMONICS:
        add(f"OP_{n} EQU {v}")
    add("")

    # ===== MAIN =====
    add("; ===== MAIN =====")
    add("START:")

    # --- Build filename and open input ---
    add("    ; Build input filename 'input.evoasm'")
    add("    ALLOC R0, 0")
    add("    FELLOWSHIP R10, R0")
    add("    FELLOWSHIP R5, R0")
    for c in "input.evoasm": add(wb(ord(c)))
    add("    WB0")
    add("    ; Open for reading")
    add("    ABOUND R0, SYS_OPEN")
    add("    FELLOWSHIP R1, R10")
    add("    ABOUND R2, MODE_READ")
    add("    RECV R0, 0")
    add("    FELLOWSHIP R12, R0       ; fd")
    add("")

    # --- Read file ---
    add("    ; Alloc input buffer (64KB via SYS_MALLOC)")
    add(alloc_large("R6", 64))
    add("    FELLOWSHIP R4, R6        ; in_buf ptr")
    add("")
    add("READ_CHUNK:")
    add("    ABOUND R0, SYS_READ")
    add("    FELLOWSHIP R1, R12")
    add("    ABOUND R3, 1")
    add("    ABOUND R14, 8")
    add("    SHL R3, R14              ; R3 = 256")
    add("    FELLOWSHIP R2, R4         ; R2 = buffer")
    add("    RECV R0, 0")
    add("    FELLOWSHIP R15, R0       ; bytes_read")
    add("    ZERO")
    add("    FELLOWSHIP R1, R0")
    add("    BRANCH R15, READ_HAS_DATA")
    add("    BRANCH R2, READ_DONE")
    add("READ_HAS_DATA:")
    add("    ABOUND R2, 1")
    add("    ABOUND R14, 8")
    add("    SHL R2, R14              ; R2 = 256")
    add("    INCREASE R4, R2")
    add("    BRANCH R2, READ_CHUNK")
    add("READ_DONE:")
    add("    ; Close input")
    add("    ABOUND R0, SYS_CLOSE")
    add("    FELLOWSHIP R1, R12")
    add("    RECV R0, 0")
    add("")
    
    # ===== PASS 1 =====
    add("    ; ===== PASS 1: Collect labels =====")
    add("    FELLOWSHIP R4, R6        ; reset ptr")
    add("    ZERO")
    add("    FELLOWSHIP R7, R1        ; R7 = addr = 0")
    add("    ; Alloc label table (32KB via SYS_MALLOC)")
    add(alloc_large("R8", 32))
    add("    ZERO")
    add("    FELLOWSHIP R13, R1       ; R13 = label count = 0")
    add("")
    add("P1_LINE:")
    add("    ; Skip leading spaces")
    add("P1_SKIP_WS:")
    add("    LOADB R1, R4")
    add("    ABOUND R2, CHAR_SP")
    add("    XOR R1, R2")
    add("    BRANCH R1, P1_CHECK_CHAR")
    add("    ABOUND R2, 1")
    add("    INCREASE R4, R2")
    add("    BRANCH R2, P1_SKIP_WS")
    add("")
    add("P1_CHECK_CHAR:")
    add("    LOADB R1, R4")
    add("    ; Null byte -> end of pass 1")
    add("    BRANCH R1, P1_CHK_CONT")
    add("    BRANCH R2, P1_END")
    add("P1_CHK_CONT:")
    add("    ; Newline -> next line")
    add("    ABOUND R2, CHAR_NL")
    add("    XOR R1, R2")
    add("    BRANCH R1, P1_NOT_NL")
    add("    ABOUND R2, 1")
    add("    INCREASE R4, R2")
    add("    BRANCH R2, P1_LINE")
    add("")
    add("P1_NOT_NL:")
    add("    ; Comment -> skip line")
    add("    ABOUND R2, CHAR_SEMI")
    add("    XOR R1, R2")
    add("    BRANCH R1, P1_NOT_COMMENT")
    add("    ; Skip comment")
    add("P1_SKIP_CMT:")
    add("    ABOUND R2, 1")
    add("    INCREASE R4, R2")
    add("    LOADB R1, R4")
    add("    BRANCH R1, P1_CMT_NL")
    add("    BRANCH R2, P1_END")
    add("P1_CMT_NL:")
    add("    ABOUND R2, CHAR_NL")
    add("    XOR R1, R2")
    add("    BRANCH R1, P1_SKIP_CMT")
    add("    BRANCH R2, P1_LINE")
    add("")
    add("P1_NOT_COMMENT:")
    add("    FELLOWSHIP R15, R4      ; R15 = line scan pointer")
    add("P1_SCAN:")
    add("    ZERO                     ; R1=0, R2=16")
    add("    PENETRATE R15, R1        ; R1 = memory[R15] (read byte)")
    add("    BRANCH R1, P1_SCN_CONT   ; non-null byte -> continue")
    add("    BRANCH R2, P1_END        ; null byte -> end of pass 1")
    add("P1_SCN_CONT:")
    add("    ABOUND R2, 1")
    add("    INCREASE R15, R2         ; R15++")
    add("    FELLOWSHIP R3, R1        ; R3 = byte (save for comparisons)")
    add("    ; Check for ':' -> label")
    add("    ABOUND R2, CHAR_COLON")
    add("    REDUCE R3, R2            ; R3 = byte - ':'")
    add("    BRANCH R3, P1_CHK_SP     ; R3 != 0 -> check space")
    add("    BRANCH R2, P1_IS_LABEL   ; R3 == 0 -> matched ':'")
    add("P1_CHK_SP:")
    add("    FELLOWSHIP R3, R1        ; R3 = byte (restore)")
    add("    ABOUND R2, CHAR_SP")
    add("    REDUCE R3, R2            ; R3 = byte - ' '")
    add("    BRANCH R3, P1_CHK_NL     ; R3 != 0 -> check newline")
    add("    BRANCH R2, P1_IS_INSN    ; R3 == 0 -> matched ' '")
    add("P1_CHK_NL:")
    add("    ABOUND R2, CHAR_NL")
    add("    REDUCE R1, R2            ; R1 = byte - '\\n'")
    add("    BRANCH R1, P1_SCAN       ; R1 != 0 -> continue scanning")
    add("    BRANCH R2, P1_IS_INSN    ; R1 == 0 -> matched '\\n'")
    add("")
    add("P1_IS_LABEL:")
    add("    ; R15 points past colon char, label name from R4 to R15-1")
    add("    ; Compute hash = sum of bytes in label name [R4, R15)")
    add("    ZERO")
    add("    FELLOWSHIP R14, R1        ; R14 = 0 (hash accumulator)")
    add("    FELLOWSHIP R2, R4         ; R2 = scan ptr = name_start")
    add("P1_HASH_LOOP:")
    add("    FELLOWSHIP R3, R2")
    add("    REDUCE R3, R15            ; R3 = R2 - end (colon ptr)")
    add("    BRANCH R3, P1_HASH_BYTE   ; R2 != R15 -> read byte")
    add("    BRANCH R2, P1_HASH_DONE   ; R2 == R15 -> done")
    add("P1_HASH_BYTE:")
    add("    ABOUND R1, 16")
    add("    ABOUND R3, 16")
    add("    REDUCE R1, R3            ; R1 = 0 (clear without ZERO macro)")
    add("    PENETRATE R2, R1          ; R1 = memory[R2]")
    add("    INCREASE R14, R1          ; hash += byte")
    add("    ABOUND R1, 1")
    add("    INCREASE R2, R1           ; R2++")
    add("    BRANCH R2, P1_HASH_LOOP")
    add("P1_HASH_DONE:")
    add("    ; R14 = hash. Store 4-byte entry: addr, hash, name_start, name_end")
    add("    DISPERSE R8, R7           ; byte0: addr")
    add("    ABOUND R2, 1")
    add("    INCREASE R8, R2")
    add("    DISPERSE R8, R14          ; byte1: hash")
    add("    INCREASE R8, R2")
    add("    DISPERSE R8, R4           ; byte2: name_start")
    add("    INCREASE R8, R2")
    add("    FELLOWSHIP R14, R15")
    add("    REDUCE R14, R2            ; R14 = R15 - 1 = name_end (last char)")
    add("    DISPERSE R8, R14          ; byte3: name_end")
    add("    INCREASE R8, R2")
    add("    INCREASE R13, R2          ; label_count++")
    add("    FELLOWSHIP R4, R14        ; R4 = name_end")
    add("    ABOUND R2, 2")
    add("    INCREASE R4, R2           ; skip ':' char")
    add("P1_SKIP_LINE:")
    add("    LOADB R1, R4")
    add("    BRANCH R1, P1_SL_CONT")
    add("    BRANCH R2, P1_END")
    add("P1_SL_CONT:")
    add("    ABOUND R2, 1")
    add("    INCREASE R4, R2")
    add("    ABOUND R2, CHAR_NL")
    add("    XOR R1, R2")
    add("    BRANCH R1, P1_SKIP_LINE")
    add("    BRANCH R2, P1_LINE")
    add("")
    add("P1_IS_INSN:")
    add("    FELLOWSHIP R2, R15")
    add("    ABOUND R15, 4")
    add("    INCREASE R7, R15         ; addr += 4")
    add("    FELLOWSHIP R4, R2")
    add("    BRANCH R2, P1_LINE")
    add("")
    add("P1_END:")
    add("    ; Save label count for Pass 2 label lookup (R10 will be preserved through Pass 2)")
    add("    FELLOWSHIP R10, R13      ; R10 = label count")
    add("    ; Pass 1 complete, continue to Pass 2")
    add("")

    # ===== PASS 2 =====
    add("    ; ===== PASS 2: Encode instructions =====")
    add("    FELLOWSHIP R4, R6        ; reset ptr")
    add("    ZERO")
    add("    FELLOWSHIP R7, R1        ; addr = 0")
    add("    ; Alloc output buffer (64KB via SYS_MALLOC)")
    add(alloc_large("R9", 64))
    add("    FELLOWSHIP R5, R9        ; output buf ptr = out base")
    add("")
    add("P2_LINE:")
    add("P2_SKIP_WS:")
    add("    LOADB R1, R4")
    add("    ABOUND R2, CHAR_SP")
    add("    XOR R1, R2")
    add("    BRANCH R1, P2_CHECK_CHAR")
    add("    ABOUND R2, 1")
    add("    INCREASE R4, R2")
    add("    BRANCH R2, P2_SKIP_WS")
    add("")
    add("P2_CHECK_CHAR:")
    add("    LOADB R1, R4")
    add("    ; Null byte -> end of pass 2")
    add("    BRANCH R1, P2_CHK_CONT")
    add("    BRANCH R2, P2_END")
    add("P2_CHK_CONT:")
    add("    ; Newline")
    add("    ABOUND R2, CHAR_NL")
    add("    XOR R1, R2")
    add("    BRANCH R1, P2_NOT_NL")
    add("    ABOUND R2, 1")
    add("    INCREASE R4, R2")
    add("    BRANCH R2, P2_LINE")
    add("")
    add("P2_NOT_NL:")
    add("    ; Comment")
    add("    ABOUND R2, CHAR_SEMI")
    add("    XOR R1, R2")
    add("    BRANCH R1, P2_NOT_CMT")
    add("P2_SKIP_CMT:")
    add("    ABOUND R2, 1")
    add("    INCREASE R4, R2")
    add("    LOADB R1, R4")
    add("    BRANCH R1, P2_SC_NL")
    add("    BRANCH R2, P2_END")
    add("P2_SC_NL:")
    add("    ABOUND R2, CHAR_NL")
    add("    XOR R1, R2")
    add("    BRANCH R1, P2_SKIP_CMT")
    add("    BRANCH R2, P2_LINE")
    add("")
    add("P2_NOT_CMT:")
    add("    ; Scan for colon (label line vs instruction)")
    add("    FELLOWSHIP R15, R4")
    add("P2_SCAN_COLON:")
    add("    LOADB R1, R15")
    add("    BRANCH R1, P2_SCO_CONT")
    add("    BRANCH R2, P2_END")
    add("P2_SCO_CONT:")
    add("    ABOUND R2, 1")
    add("    INCREASE R15, R2")
    add("    FELLOWSHIP R3, R1         ; save byte")
    add("    ABOUND R2, CHAR_COLON")
    add("    REDUCE R3, R2             ; R3 = byte - ':'")
    add("    BRANCH R3, P2_CHK_NL2     ; not ':'")
    add("    BRANCH R2, P2_IS_LABEL_LINE ; is ':', skip label line")
    add("P2_CHK_NL2:")
    add("    ABOUND R2, CHAR_NL")
    add("    REDUCE R1, R2             ; R1 = byte - '\\n'")
    add("    BRANCH R1, P2_SCAN_COLON  ; not '\\n', continue scan")
    add("    BRANCH R2, P2_ENCODE      ; is '\\n', encode instruction")
    add("")
    add("P2_IS_LABEL_LINE:")
    add("    FELLOWSHIP R4, R15")
    add("P2_AFTER_COLON:")
    add("    LOADB R1, R4")
    add("    BRANCH R1, P2_AC_CONT")
    add("    BRANCH R2, P2_END")
    add("P2_AC_CONT:")
    add("    ABOUND R2, 1")
    add("    INCREASE R4, R2")
    add("    ABOUND R2, CHAR_NL")
    add("    XOR R1, R2")
    add("    BRANCH R1, P2_AFTER_COLON")
    add("    BRANCH R2, P2_LINE")
    add("")

    # ===== Mnemonic recognition =====
    add("    ; ===== Mnemonic Recognition =====")
    add("P2_ENCODE:")
    add("    LOADB R1, R4              ; First char of token")
    add("    FELLOWSHIP R12, R4        ; Save R4 starting position for NOT_xxx restore")
    for name, opcode in MNEMONICS:
        cb = [ord(c) for c in name]
        add(f"    ; Check '{name}'")
        add(f"    ABOUND R2, {cb[0]}")
        add("    XOR R1, R2")
        add(f"    BRANCH R1, NOT_{name}")
        add(f"    ABOUND R2, 1")
        add(f"    INCREASE R4, R2")
        for i in range(1, len(cb)):
            add(f"    LOADB R1, R4")
            add(f"    ABOUND R2, {cb[i]}")
            add("    XOR R1, R2")
            if i < len(cb) - 1:
                add(f"    BRANCH R1, NOT_{name}")
            add(f"    ABOUND R2, 1")
            add(f"    INCREASE R4, R2")
        add(f"    ABOUND R11, OP_{name}")
        add(f"    FELLOWSHIP R11, R11")
        add(f"    BRANCH R2, P2_PARSE_OPERANDS")
        add(f"NOT_{name}:")
        if name != MNEMONICS[-1][0]:
            add("    FELLOWSHIP R4, R12        ; Restore R4 to line start using saved R12")
            add("    LOADB R1, R4              ; Reload first char from correct position")
    add("    ; Unknown mnemonic - skip line")
    add("P2_SKIP_LINE2:")
    add("    ABOUND R2, 1")
    add("    INCREASE R4, R2")
    add("    LOADB R1, R4")
    add("    BRANCH R1, P2_SL2_CONT")
    add("    BRANCH R2, P2_END")
    add("P2_SL2_CONT:")
    add("    ABOUND R2, CHAR_NL")
    add("    XOR R1, R2")
    add("    BRANCH R1, P2_SKIP_LINE2")
    add("    BRANCH R2, P2_LINE")
    add("")

    # ===== Operand parsing =====
    add("    ; ===== Operand Parsing =====")
    add("P2_PARSE_OPERANDS:")
    add("    ; R4 points past mnemonic name, R11 = opcode")
    add("    ; Goal: R13 = operand1 byte, R14 = operand2 byte")
    add("")
    add("    ; --- Skip spaces before operand1 ---")
    add("P2_PO_SKIPSP1:")
    add("    LOADB R1, R4")
    add("    ABOUND R2, 32           ; ' '")
    add("    XOR R1, R2")
    add("    BRANCH R1, P2_PO_READ1")
    add("    ABOUND R2, 1")
    add("    INCREASE R4, R2")
    add("    BRANCH R2, P2_PO_SKIPSP1")
    add("")
    add("P2_PO_READ1:")
    add("    LOADB R1, R4            ; first char of operand1")
    add("    ; Check for newline -> 0-operand instruction (e.g., HALT)")
    add("    ABOUND R2, CHAR_NL")
    add("    XOR R1, R2")
    add("    BRANCH R1, P2_PO_RD1_NL  ; not newline, continue")
    add("    BRANCH R2, P2_EMIT       ; newline -> emit (0-operand)")
    add("P2_PO_RD1_NL:")
    add("    LOADB R1, R4            ; reload (R1 was clobbered by XOR above)")
    add("    ; Check for register 'R' (82)")
    add("    ABOUND R2, 82")
    add("    XOR R1, R2")
    add("    BRANCH R1, P2_PO_OP1NUM ; not 'R', parse as number")
    add("    ; --- Parse register ---")
    add("    ABOUND R2, 1")
    add("    INCREASE R4, R2         ; skip 'R'")
    add("    LOADB R13, R4           ; first digit char")
    add("    ABOUND R2, 1")
    add("    INCREASE R4, R2")
    add("    ABOUND R2, 48           ; '0'")
    add("    REDUCE R13, R2          ; R13 = digit value")
    add("    ; Check if 2-digit register (R10-R15)")
    add("    LOADB R1, R4            ; peek next char")
    add("    ABOUND R2, 32           ; ' '")
    add("    XOR R1, R2")
    add("    BRANCH R1, P2_PO_REG2DIG ; not space, could be 2nd digit")
    add("    BRANCH R2, P2_PO_SKIPCOMMA ; space, done with op1")
    add("P2_PO_REG2DIG:")
    add("    LOADB R1, R4            ; could be digit or comma")
    add("    ABOUND R2, 44           ; ','")
    add("    XOR R1, R2")
    add("    BRANCH R1, P2_PO_REG2DIG2 ; not comma -> parse 2nd digit")
    add("    BRANCH R2, P2_PO_SKIPCOMMA ; comma, done")
    add("P2_PO_REG2DIG2:")
    add("    ; Parse 2nd digit for register R10-R15")
    add("    ABOUND R2, 1")
    add("    INCREASE R4, R2         ; skip digit char")
    add("    ; R13 = R13 * 10 + digit")
    add("    ABOUND R2, 48           ; '0'")
    add("    REDUCE R1, R2           ; R1 = digit value")
    add("    ; Multiply R13 by 10: R13 = R13*8 + R13*2")
    add("    FELLOWSHIP R14, R13     ; save original")
    add("    ABOUND R3, 3")
    add("    SHL R13, R3             ; R13 = R13 * 8")
    add("    ABOUND R3, 1")
    add("    SHL R14, R3             ; R14 = original * 2")
    add("    INCREASE R13, R14       ; R13 = R13*8 + R13*2 = R13*10")
    add("    INCREASE R13, R1        ; R13 = R13*10 + digit")
    add("    BRANCH R2, P2_PO_SKIPCOMMA")
    add("")
    add("    ; --- Parse number operand ---")
    add("P2_PO_OP1NUM:")
    add("    LOADB R1, R4            ; first digit char (re-read)")
    add("    ZERO")
    add("    FELLOWSHIP R13, R1      ; R13 = 0 (accumulator)")
    add("P2_PO_NUM1_LOOP:")
    add("    LOADB R1, R4            ; current char")
    add("    ; Check if digit (between '0' and '9')")
    add("    ABOUND R2, 48           ; '0'")
    add("    REDUCE R1, R2           ; R1 = char - '0'")
    add("    ; Check if R1 >= 10 (not a digit in 0-9 range)")
    add("    FELLOWSHIP R14, R1      ; save digit value")
    add("    ABOUND R2, 10")
    add("    ; We can't directly compare. Use: digit_value - 10, check negative")
    add("    ; But VM has no sign check for branch... Let's check if value > 10")
    add("    ; Approach: if value in 0-9 range, the value < 10 in unsigned")
    add("    ; We'll just proceed assuming it's a digit for well-formed input")
    add("    ; Actually, check common non-digit chars: space=32(-> -16), comma=44(-> -4)")
    add("    BRANCH R14, P2_PO_NUM1BODY  ; if non-zero, might be digit or other")
    add("    ; R14 == 0 means char == '0' (digit), process")
    add("    BRANCH R2, P2_PO_NUM1BODY")
    add("P2_PO_NUM1BODY:")
    add("    ; R13 = R13 * 10 + digit(R14)")
    add("    FELLOWSHIP R15, R13     ; save old value")
    add("    ABOUND R3, 3")
    add("    SHL R13, R3             ; *8")
    add("    ABOUND R3, 1")
    add("    SHL R15, R3             ; *2")
    add("    INCREASE R13, R15       ; *10")
    add("    INCREASE R13, R14       ; + digit")
    add("    ABOUND R2, 1")
    add("    INCREASE R4, R2         ; advance past digit")
    add("    ; Peek next char")
    add("    LOADB R1, R4")
    add("    ABOUND R2, 44           ; ','")
    add("    XOR R1, R2")
    add("    BRANCH R1, P2_PO_CHK_SP2 ; not comma")
    add("    BRANCH R2, P2_PO_SKIPCOMMA ; comma, done")
    add("P2_PO_CHK_SP2:")
    add("    ; Check for newline (end of line, no operand2)")
    add("    LOADB R1, R4            ; reload peek char")
    add("    ABOUND R2, CHAR_NL")
    add("    XOR R1, R2")
    add("    BRANCH R1, P2_PO_CHK_SP2A ; not newline, check space")
    add("    BRANCH R2, P2_EMIT       ; newline -> emit (1-operand)")
    add("P2_PO_CHK_SP2A:")
    add("    ABOUND R2, 32           ; ' '")
    add("    XOR R1, R2")
    add("    BRANCH R1, P2_PO_NUM1_LOOP ; not space, continue parsing digits")
    add("    BRANCH R2, P2_PO_SKIPSP2 ; space, done with op1")
    add("")
    add("    ; --- Skip comma and spaces to operand2 ---")
    add("P2_PO_SKIPCOMMA:")
    add("    LOADB R1, R4")
    add("    ABOUND R2, 44           ; ','")
    add("    XOR R1, R2")
    add("    BRANCH R1, P2_PO_SKIPSP2 ; no comma, just spaces")
    add("    ABOUND R2, 1")
    add("    INCREASE R4, R2         ; skip comma")
    add("P2_PO_SKIPSP2:")
    add("    LOADB R1, R4")
    add("    ABOUND R2, 32           ; ' '")
    add("    XOR R1, R2")
    add("    BRANCH R1, P2_PO_READ2")
    add("    ABOUND R2, 1")
    add("    INCREASE R4, R2")
    add("    BRANCH R2, P2_PO_SKIPSP2")
    add("")
    add("    ; --- Parse operand2 (same pattern as operand1) ---")
    add("P2_PO_READ2:")
    add("    LOADB R1, R4")
    add("    ABOUND R2, 82           ; 'R'")
    add("    XOR R1, R2")
    add("    BRANCH R1, P2_PO_OP2NUM ; not 'R', check for label or number")
    add("    ; Register")
    add("    ABOUND R2, 1")
    add("    INCREASE R4, R2")
    add("    LOADB R14, R4")
    add("    ABOUND R2, 1")
    add("    INCREASE R4, R2")
    add("    ABOUND R2, 48")
    add("    REDUCE R14, R2          ; R14 = digit value")
    add("    ; Check 2nd digit")
    add("    LOADB R1, R4")
    add("    ABOUND R2, 32")
    add("    XOR R1, R2")
    add("    BRANCH R1, P2_PO_REG2DIG2B")
    add("    BRANCH R2, P2_EMIT")
    add("P2_PO_REG2DIG2B:")
    add("    LOADB R1, R4")
    add("    ABOUND R2, 44")
    add("    XOR R1, R2")
    add("    BRANCH R1, P2_PO_R2_DIG2")
    add("    BRANCH R2, P2_EMIT")
    add("P2_PO_R2_DIG2:")
    add("    ABOUND R2, 1")
    add("    INCREASE R4, R2")
    add("    ABOUND R2, 48")
    add("    REDUCE R1, R2")
    add("    FELLOWSHIP R15, R14")
    add("    ABOUND R3, 3")
    add("    SHL R14, R3")
    add("    ABOUND R3, 1")
    add("    SHL R15, R3")
    add("    INCREASE R14, R15")
    add("    INCREASE R14, R1")
    add("    BRANCH R2, P2_EMIT")
    add("")
    add("    ; --- Check if operand2 is label name or number ---")
    add("P2_PO_OP2NUM:")
    add("    ; Check high nibble: digits have 0x30-0x39 (high nibble 0x30)")
    add("    ; Labels start with A-Z (0x41-0x5A), _ (0x5F), or @ (0x40)")
    add("    LOADB R14, R4           ; first char")
    add("    ; Save operand start pointer for label lookup (R10 = label count)")
    add("    FELLOWSHIP R15, R4      ; R15 = operand start")
    add("    ; Check (char & 0xF0) == 0x30")
    add("    FELLOWSHIP R1, R14")
    add("    ABOUND R2, 0xF0")
    add("    AND R1, R2              ; R1 = char & 0xF0")
    add("    ABOUND R2, 0x30")
    add("    XOR R1, R2              ; R1 = 0 if high nibble is 0x30 (digit)")
    add("    BRANCH R1, P2_PO_OP2LABEL ; high nibble != 0x30 -> label name!")
    add("    ; Falls through: high nibble == 0x30 -> parse as number")
    add("    BRANCH R2, P2_PO_OP2ASNUM")
    add("")
    add("P2_PO_OP2ASNUM:")
    add("    ; Parse number for operand2")
    add("    ZERO")
    add("    FELLOWSHIP R14, R1      ; R14 = 0")
    add("    BRANCH R2, P2_PO_NUM2_LOOP")
    add("")
    add("P2_PO_NUM2_LOOP:")
    add("    LOADB R1, R4")
    add("    ABOUND R2, 48")
    add("    REDUCE R1, R2           ; R1 = char - '0'")
    add("    FELLOWSHIP R15, R1      ; save digit")
    add("    ; Check for end: space or newline")
    add("    ABOUND R2, 1")
    add("    INCREASE R4, R2")
    add("    LOADB R1, R4            ; peek next")
    add("    ABOUND R2, 32")
    add("    XOR R1, R2")
    add("    BRANCH R1, P2_PO_N2_CHKNL")
    add("    ; Next is space, process digit")
    add("    FELLOWSHIP R1, R15")
    add("    BRANCH R2, P2_PO_N2_ACCUM")
    add("P2_PO_N2_CHKNL:")
    add("    ABOUND R2, 10           ; newline")
    add("    XOR R1, R2")
    add("    BRANCH R1, P2_PO_N2_CONT")
    add("    ; Next is newline, process digit")
    add("    FELLOWSHIP R1, R15")
    add("    BRANCH R2, P2_PO_N2_ACCUM")
    add("P2_PO_N2_CONT:")
    add("    ; More digits")
    add("    FELLOWSHIP R1, R15")
    add("P2_PO_N2_ACCUM:")
    add("    ; R14 = R14 * 10 + digit(R1)")
    add("    FELLOWSHIP R15, R14")
    add("    ABOUND R3, 3")
    add("    SHL R14, R3")
    add("    ABOUND R3, 1")
    add("    SHL R15, R3")
    add("    INCREASE R14, R15")
    add("    INCREASE R14, R1")
    add("    ; Peek next")
    add("    LOADB R1, R4")
    add("    ABOUND R2, 32")
    add("    XOR R1, R2")
    add("    BRANCH R1, P2_PO_N2_NL")
    add("    BRANCH R2, P2_EMIT      ; space → done")
    add("P2_PO_N2_NL:")
    add("    ABOUND R2, 10")
    add("    XOR R1, R2")
    add("    BRANCH R1, P2_PO_NUM2_LOOP ; continue")
    add("    BRANCH R2, P2_EMIT      ; newline → done")
    add("")

    # ===== Label operand lookup =====
    add("    ; --- Label operand2 lookup ---")
    add("P2_PO_OP2LABEL:")
    add("    ; R15 = operand start, R10 = label count, R8 = label table")
    add("    ; Table entry format (4 bytes): addr, hash, name_start, name_end")
    add("    ; Step 1: Scan forward to find end of operand (space or newline)")
    add("    FELLOWSHIP R4, R15      ; R4 = scan = operand start")
    add("P2_LB_FINDEND:")
    add("    ABOUND R2, 1")
    add("    INCREASE R4, R2          ; R4++")
    add("    LOADB R1, R4             ; peek next char")
    add("    ABOUND R2, CHAR_SP")
    add("    XOR R1, R2")
    add("    BRANCH R1, P2_LB_FE_NL   ; not space, check newline")
    add("    BRANCH R2, P2_LB_ENDOK   ; space, end found")
    add("P2_LB_FE_NL:")
    add("    LOADB R1, R4             ; reload (XOR clobbered R1)")
    add("    ABOUND R2, CHAR_NL")
    add("    XOR R1, R2")
    add("    BRANCH R1, P2_LB_FINDEND ; not newline, continue scan")
    add("    ; Falls through: newline -> end found")
    add("P2_LB_ENDOK:")
    add("    ; R15 = start, R4 = end (points to delimiting char)")
    add("    ; Step 2: Compute hash = sum of bytes in [R15, R4)")
    add("    ZERO")
    add("    FELLOWSHIP R14, R1       ; R14 = 0 (hash accumulator)")
    add("    FELLOWSHIP R12, R15      ; R12 = scan ptr = start")
    add("P2_LB_HASH_LOOP:")
    add("    FELLOWSHIP R1, R12")
    add("    REDUCE R1, R4            ; R1 = R12 - end")
    add("    BRANCH R1, P2_LB_HASH_BYTE ; not done yet")
    add("    BRANCH R2, P2_LB_HASH_DONE  ; done")
    add("P2_LB_HASH_BYTE:")
    add("    ZERO                     ; R1=0")
    add("    PENETRATE R12, R1         ; R1 = memory[R12]")
    add("    INCREASE R14, R1          ; hash += byte")
    add("    ABOUND R1, 1")
    add("    INCREASE R12, R1          ; R12++")
    add("    BRANCH R2, P2_LB_HASH_LOOP")
    add("P2_LB_HASH_DONE:")
    add("    ; R14 = operand hash. Search label table (4-byte entries)")
    add("    FELLOWSHIP R12, R8        ; R12 = table ptr")
    add("    ZERO")
    add("    FELLOWSHIP R3, R1         ; R3 = 0 (entry counter)")
    add("P2_LB_SRCH_LOOP:")
    add("    FELLOWSHIP R1, R3")
    add("    REDUCE R1, R10            ; R1 = counter - count")
    add("    BRANCH R1, P2_LB_NEXT_ENT ; not done yet")
    add("    BRANCH R2, P2_LB_NOTFOUND ; all entries searched")
    add("P2_LB_NEXT_ENT:")
    add("    ; Save counter before ZERO clobbers it")
    add("    FELLOWSHIP R0, R3         ; R0 = counter (temp save)")
    add("    ; Read addr byte (byte0 of entry)")
    add("    ZERO")
    add("    PENETRATE R12, R1         ; R1 = addr byte")
    add("    FELLOWSHIP R15, R1        ; R15 = addr (reuse R15, no longer needed)")
    add("    ABOUND R1, 1")
    add("    INCREASE R12, R1          ; R12++ (skip addr)")
    add("    ; Read hash byte (byte1 of entry)")
    add("    ZERO")
    add("    PENETRATE R12, R1         ; R1 = hash byte")
    add("    XOR R1, R14               ; compare with operand hash")
    add("    BRANCH R1, P2_LB_NOMATCH  ; hash doesn't match")
    add("    ; Match! Use addr from R15")
    add("    FELLOWSHIP R14, R15       ; R14 = addr (operand2 value)")
    add("    BRANCH R2, P2_EMIT         ; done, write instruction")
    add("P2_LB_NOMATCH:")
    add("    ; Skip name_start, name_end (2 bytes) to reach next entry")
    add("    ABOUND R1, 2")
    add("    INCREASE R12, R1          ; R12 += 2")
    add("    ; Restore and increment counter")
    add("    FELLOWSHIP R3, R0         ; R3 = saved counter")
    add("    ABOUND R1, 1")
    add("    INCREASE R3, R1           ; counter++")
    add("    BRANCH R2, P2_LB_SRCH_LOOP")
    add("P2_LB_NOTFOUND:")
    add("    ; Label not found - use 0 as placeholder")
    add("    ZERO")
    add("    FELLOWSHIP R14, R1        ; R14 = 0")
    add("    BRANCH R2, P2_EMIT")
    add("")

    # ===== Emit instruction =====
    add("    ; ===== Emit 4-byte instruction =====")
    add("P2_EMIT:")
    add("    ; byte1 = opcode << 2")
    add("    ABOUND R3, 1")
    add("    FELLOWSHIP R1, R11")
    add("    SHL R1, R3")
    add("    SHL R1, R3")
    add("    DISPERSE R5, R1")
    add("    ABOUND R2, 1")
    add("    INCREASE R5, R2")
    add("    ; byte2 = 0  (modifier byte)")
    add("    ZERO")
    add("    DISPERSE R5, R1")
    add("    INCREASE R5, R2")
    add("    ; byte3 = operand1 (from R13)")
    add("    FELLOWSHIP R1, R13")
    add("    DISPERSE R5, R1")
    add("    INCREASE R5, R2")
    add("    ; byte4 = operand2 (from R14)")
    add("    FELLOWSHIP R1, R14")
    add("    DISPERSE R5, R1")
    add("    INCREASE R5, R2")
    add("    ; addr += 4")
    add("    ABOUND R2, 4")
    add("    INCREASE R7, R2")
    add("")
    add("    ; Skip to next line")
    add("P2_TO_NL:")
    add("    LOADB R1, R4")
    add("    BRANCH R1, P2_TNL_CONT")
    add("    BRANCH R2, P2_END")
    add("P2_TNL_CONT:")
    add("    ABOUND R2, 1")
    add("    INCREASE R4, R2")
    add("    ABOUND R2, CHAR_NL")
    add("    XOR R1, R2")
    add("    BRANCH R1, P2_TO_NL")
    add("    BRANCH R2, P2_LINE")
    add("")
    add("P2_END:")
    add("    ; Pass 2 complete")
    add("")

    # ===== Done =====
    add("DONE:")
    add("    ; Calculate output size: R5 - R9")
    add("    FELLOWSHIP R1, R5")
    add("    REDUCE R1, R9")
    add("    FELLOWSHIP R13, R1")
    add("")
    add("    ; Build 'output.evob' filename")
    add("    ALLOC R0, 0")
    add("    FELLOWSHIP R10, R0     ; Save base for later SYS_OPEN (R14 corrupt by long jumps)")
    add("    FELLOWSHIP R5, R0")
    for c in "output.evob": add(wb(ord(c)))
    add("    WB0")
    add("")
    add("    ; Open output file")
    add("    ABOUND R0, SYS_OPEN")
    add("    FELLOWSHIP R1, R10     ; Use saved base (R5 was advanced by wb())")
    add("    ABOUND R2, MODE_WRITE")
    add("    RECV R0, 0")
    add("    FELLOWSHIP R12, R0")
    add("")
    add("    ; Write bytecode")
    add("    ABOUND R0, SYS_WRITE")
    add("    FELLOWSHIP R1, R12")
    add("    FELLOWSHIP R2, R9")
    add("    FELLOWSHIP R3, R13")
    add("    RECV R0, 0")
    add("")
    add("    ; Close & exit")
    add("    ABOUND R0, SYS_CLOSE")
    add("    FELLOWSHIP R1, R12")
    add("    RECV R0, 0")
    add("    ABOUND R0, SYS_EXIT")
    add("    RECV R0, 0")
    add("HALT")

    return "\n".join(L)

if __name__ == "__main__":
    print(gen())
